Repository EddieDover/Theater-of-the-Mind, pull requests merged in 2024-02, with the labels that each got.

#30 fix: template loading call now only happens on GM machine
  src/module/theater-of-the-mind.js
Labels: bug

#31 fix: array-string-builder now properly accesses sets
  src/module/app/party-sheet.js
Labels: bug

#34 Changes to example_templates
  README.md
  SYSTEMS.md
  example_templates/alienrpg.json
  example_templates/blade-runner-basic.json
  example_templates/blade-runner-expanded.json
  example_templates/dnd5e_modified.json
  example_templates/dragonbane-name.json
  example_templates/dragonbane-no-name.json
  example_templates/fallout.json
  example_templates/starfinder.json
  example_templates/twdu-anchors.json
  example_templates/twdu-no-anchors.json
  example_templates/twdu-two-rows.json
Labels: enhancement

#32 v2.0.1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/template_submission.md
  README.md
  TEMPLATE_LIST.md
  TEMPLATE_README.md
  example_templates/alienrpg/alienrpg.jpg
  example_templates/alienrpg/alienrpg.json
  example_templates/blade-runner/blade-runner-basic.jpg
  example_templates/blade-runner/blade-runner-basic.json
  example_templates/blade-runner/blade-runner-expanded.jpg
  example_templates/blade-runner/blade-runner-expanded.json
  example_templates/dnd5e/dnd5e_modified.jpg
  example_templates/dnd5e/dnd5e_modified.json
  example_templates/dnd5e/dnd5e_template.jpg
  example_templates/dnd5e/dnd5e_template.json
  example_templates/dragonbane/dragonbane-name.jpg
  example_templates/dragonbane/dragonbane-name.json
  example_templates/dragonbane/dragonbane-no-name.jpg
  example_templates/dragonbane/dragonbane-no-name.json
  example_templates/fallout/fallout.jpg
  example_templates/fallout/fallout.json
  example_templates/no-game.png
  example_templates/starfinder/starfinder.jpg
  example_templates/starfinder/starfinder.json
  example_templates/thewalkingdead/twddu-anchors.jpg
  example_templates/thewalkingdead/twdu-anchors.jpg
  example_templates/thewalkingdead/twdu-anchors.json
  example_templates/thewalkingdead/twdu-no-anchors.jpg
  example_templates/thewalkingdead/twdu-no-anchors.json
  example_templates/thewalkingdead/twdu-two-rows.jpg
  example_templates/thewalkingdead/twdu-two-rows.json
  example_templates/vaesen/vaesen.jpg
  example_templates/vaesen/vaesen.json
  images/fgps.png
  images/preview1.png
  images/preview2.png
  package.json
  src/module.json
  src/module/app/party-sheet.js
  src/module/theater-of-the-mind.js
Labels: bug

#52 Fix readme links
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: bug, documentation

#59 feat(templates): added italics and bold tags
  .versionrc
  TEMPLATE_README.md
  package-lock.json
  package.json
  src/module/app/party-sheet.js
Labels: enhancement

#66 Implements Largest-From-Array and Smallest-From-Array
  .vscode/settings.json
  TEMPLATE_README.md
  doc_images/ls_results.png
  doc_images/pf1e_stats.png
  image.png
  rollup.config.mjs
  src/module/app/party-sheet.js
  src/module/utils.js
Labels: enhancement
